[2025-03-19T04:52:26.564+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/other.py
[2025-03-19T04:52:26.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:52:26.575+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:52:26.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:52:26.694+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:52:26.665+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:52:26.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:52:26.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.262 seconds
[2025-03-19T04:52:57.794+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/other.py
[2025-03-19T04:52:57.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:52:57.808+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:52:57.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:52:57.857+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:52:57.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:52:57.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:52:57.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.165 seconds
[2025-03-19T04:53:29.019+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/other.py
[2025-03-19T04:53:29.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:53:29.026+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:53:29.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:53:29.070+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:53:29.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:53:29.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:53:29.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.132 seconds
[2025-03-19T04:54:00.246+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/other.py
[2025-03-19T04:54:00.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:54:00.252+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:54:00.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:54:00.296+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:54:00.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:54:00.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:54:00.376+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.140 seconds
[2025-03-19T04:54:30.627+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/other.py
[2025-03-19T04:54:30.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:54:30.633+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:54:30.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:54:30.678+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:54:30.666+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:54:30.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:54:30.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.138 seconds
[2025-03-19T04:55:02.019+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/other.py
[2025-03-19T04:55:02.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:55:02.026+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:55:02.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:55:02.069+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:55:02.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:55:02.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:55:02.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.142 seconds
[2025-03-19T04:55:21.907+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/other.py
[2025-03-19T04:55:21.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:55:21.915+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:55:21.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:55:21.976+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:55:21.969+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake_operator import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.operators.snowflake_operator'
[2025-03-19T04:55:21.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:55:22.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.134 seconds
[2025-03-19T04:55:52.419+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/other.py
[2025-03-19T04:55:52.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:55:52.424+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:55:52.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:55:52.457+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:55:52.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake_operator import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake.operators.snowflake_operator'
[2025-03-19T04:55:52.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:55:52.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.098 seconds
[2025-03-19T04:56:05.247+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/other.py
[2025-03-19T04:56:05.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:56:05.254+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:56:05.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:56:05.351+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:56:05.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:56:05.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:56:05.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.174 seconds
[2025-03-19T04:56:35.559+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/other.py
[2025-03-19T04:56:35.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:56:35.565+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:56:35.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:56:35.610+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:56:35.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:56:35.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:56:35.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.124 seconds
[2025-03-19T04:57:05.971+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/other.py
[2025-03-19T04:57:05.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:57:05.979+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:57:05.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:57:06.034+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:57:06.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:57:06.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:57:06.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.142 seconds
[2025-03-19T04:57:37.405+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/other.py
[2025-03-19T04:57:37.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:57:37.411+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:57:37.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:57:37.480+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:57:37.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:57:37.485+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:57:37.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.149 seconds
[2025-03-19T04:57:38.810+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/other.py
[2025-03-19T04:57:38.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:57:38.818+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:57:38.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:57:38.906+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:57:38.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:57:38.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:57:38.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.185 seconds
[2025-03-19T04:58:09.216+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/other.py
[2025-03-19T04:58:09.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:58:09.221+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:58:09.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:58:09.267+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:58:09.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:58:09.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:58:09.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.142 seconds
[2025-03-19T04:58:39.575+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/other.py
[2025-03-19T04:58:39.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:58:39.580+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:58:39.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:58:39.622+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:58:39.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:58:39.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:58:39.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.128 seconds
[2025-03-19T04:59:12.352+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/other.py
[2025-03-19T04:59:12.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:59:12.370+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:59:12.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:59:12.465+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:59:12.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:59:12.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:59:12.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.252 seconds
[2025-03-19T04:59:42.960+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/other.py
[2025-03-19T04:59:42.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T04:59:42.966+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:59:42.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T04:59:42.990+0000] {logging_mixin.py:190} INFO - [2025-03-19T04:59:42.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T04:59:42.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T04:59:43.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.092 seconds
[2025-03-19T05:00:13.364+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/other.py
[2025-03-19T05:00:13.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:00:13.369+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:00:13.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:00:13.420+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:00:13.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T05:00:13.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:00:13.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.141 seconds
[2025-03-19T05:00:44.300+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/other.py
[2025-03-19T05:00:44.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:00:44.305+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:00:44.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:00:44.338+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:00:44.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T05:00:44.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:00:44.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.104 seconds
[2025-03-19T05:01:14.963+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/other.py
[2025-03-19T05:01:14.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:01:14.967+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:01:14.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:01:15.008+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:01:14.997+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T05:01:15.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:01:15.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.132 seconds
[2025-03-19T05:02:06.285+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/other.py
[2025-03-19T05:02:06.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:02:06.291+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:02:06.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:02:06.346+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:02:06.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T05:02:06.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:02:06.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.153 seconds
[2025-03-19T05:02:37.002+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/other.py
[2025-03-19T05:02:37.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:02:37.007+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:02:37.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:02:37.050+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:02:37.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/other.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/other.py", line 11, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ImportError: cannot import name 'SnowflakeOperator' from 'airflow.providers.snowflake.operators.snowflake' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/operators/snowflake.py)
[2025-03-19T05:02:37.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:02:37.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.133 seconds
[2025-03-19T05:02:56.264+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/other.py
[2025-03-19T05:02:56.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:02:56.269+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:02:56.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:02:56.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:02:56.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.121 seconds
[2025-03-19T05:03:27.143+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/other.py
[2025-03-19T05:03:27.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:03:27.158+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:03:27.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:03:27.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:03:27.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.146 seconds
[2025-03-19T05:03:57.719+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/other.py
[2025-03-19T05:03:57.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:03:57.725+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:03:57.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:03:57.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:03:57.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.057 seconds
[2025-03-19T05:04:28.466+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/other.py
[2025-03-19T05:04:28.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:04:28.471+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:04:28.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:04:28.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:04:28.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.086 seconds
[2025-03-19T05:04:59.836+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/other.py
[2025-03-19T05:04:59.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:04:59.841+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:04:59.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:04:59.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:04:59.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.067 seconds
[2025-03-19T05:05:30.641+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/other.py
[2025-03-19T05:05:30.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:05:30.649+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:05:30.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:05:30.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:05:30.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.100 seconds
[2025-03-19T05:06:01.094+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/other.py
[2025-03-19T05:06:01.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:06:01.099+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:06:01.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:06:01.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:06:01.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.069 seconds
[2025-03-19T05:06:31.973+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/other.py
[2025-03-19T05:06:31.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:06:31.982+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:06:31.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:06:32.021+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:06:32.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.093 seconds
[2025-03-19T05:07:03.099+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/other.py
[2025-03-19T05:07:03.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:07:03.105+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:07:03.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:07:03.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:07:03.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.119 seconds
[2025-03-19T05:07:33.982+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/other.py
[2025-03-19T05:07:33.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:07:33.987+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:07:33.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:07:34.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:07:34.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.062 seconds
[2025-03-19T05:08:05.038+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/other.py
[2025-03-19T05:08:05.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:08:05.044+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:08:05.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:08:05.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:08:05.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.081 seconds
[2025-03-19T05:08:36.228+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/other.py
[2025-03-19T05:08:36.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:08:36.233+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:08:36.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:08:36.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:08:36.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.085 seconds
[2025-03-19T05:09:07.628+0000] {processor.py:186} INFO - Started process (PID=248) to work on /opt/airflow/dags/other.py
[2025-03-19T05:09:07.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:09:07.632+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:09:07.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:09:07.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:09:07.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.076 seconds
[2025-03-19T05:09:37.926+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/other.py
[2025-03-19T05:09:37.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:09:37.929+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:09:37.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:09:37.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:09:38.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.083 seconds
[2025-03-19T05:10:09.372+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/other.py
[2025-03-19T05:10:09.374+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:10:09.375+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:10:09.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:10:09.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:10:09.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.059 seconds
[2025-03-19T05:10:39.997+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/other.py
[2025-03-19T05:10:39.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:10:40.001+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:10:40.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:10:40.027+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:10:40.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.070 seconds
[2025-03-19T05:11:10.195+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/other.py
[2025-03-19T05:11:10.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:11:10.198+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:11:10.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:11:10.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:11:10.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.080 seconds
[2025-03-19T05:11:40.473+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/other.py
[2025-03-19T05:11:40.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:11:40.476+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:11:40.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:11:40.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:11:40.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.059 seconds
[2025-03-19T05:12:27.046+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/other.py
[2025-03-19T05:12:27.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:12:27.050+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:12:27.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:12:27.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:12:27.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.070 seconds
[2025-03-19T05:12:58.372+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/other.py
[2025-03-19T05:12:58.374+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:12:58.376+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:12:58.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:12:58.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:12:58.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.064 seconds
[2025-03-19T05:13:28.809+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/other.py
[2025-03-19T05:13:28.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:13:28.813+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:13:28.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:13:28.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:13:28.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.062 seconds
[2025-03-19T05:13:59.195+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/other.py
[2025-03-19T05:13:59.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:13:59.198+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:13:59.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:13:59.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:13:59.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.066 seconds
[2025-03-19T05:14:29.798+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/other.py
[2025-03-19T05:14:29.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:14:29.802+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:14:29.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:14:29.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:14:29.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.072 seconds
[2025-03-19T05:15:01.010+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/other.py
[2025-03-19T05:15:01.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:15:01.015+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:15:01.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:15:01.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:15:01.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.093 seconds
[2025-03-19T05:15:31.986+0000] {processor.py:186} INFO - Started process (PID=363) to work on /opt/airflow/dags/other.py
[2025-03-19T05:15:31.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:15:31.989+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:15:31.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:15:32.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:15:32.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.061 seconds
[2025-03-19T05:16:03.346+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/other.py
[2025-03-19T05:16:03.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:16:03.352+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:16:03.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:16:03.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:16:03.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.095 seconds
[2025-03-19T05:16:34.855+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/other.py
[2025-03-19T05:16:34.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:16:34.858+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:16:34.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:16:34.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:16:34.899+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.050 seconds
[2025-03-19T05:17:06.573+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/other.py
[2025-03-19T05:17:06.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:17:06.577+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:17:06.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:17:06.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:17:06.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.075 seconds
[2025-03-19T05:17:37.675+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/other.py
[2025-03-19T05:17:37.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/other.py for tasks to queue
[2025-03-19T05:17:37.679+0000] {logging_mixin.py:190} INFO - [2025-03-19T05:17:37.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/other.py
[2025-03-19T05:17:37.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/other.py
[2025-03-19T05:17:37.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/other.py took 0.068 seconds
