[2025-03-16T19:08:41.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T19:08:41.498+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.print_random_quote manual__2025-03-16T19:08:22.500968+00:00 [queued]>
[2025-03-16T19:08:41.531+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.print_random_quote manual__2025-03-16T19:08:22.500968+00:00 [queued]>
[2025-03-16T19:08:41.533+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-16T19:08:41.598+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): print_random_quote> on 2025-03-16 19:08:22.500968+00:00
[2025-03-16T19:08:41.609+0000] {standard_task_runner.py:72} INFO - Started process 293 to run task
[2025-03-16T19:08:41.615+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'print_random_quote', 'manual__2025-03-16T19:08:22.500968+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmp5ji0pisb']
[2025-03-16T19:08:41.618+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask print_random_quote
[2025-03-16T19:08:41.868+0000] {task_command.py:467} INFO - Running <TaskInstance: welcome_dag.print_random_quote manual__2025-03-16T19:08:22.500968+00:00 [running]> on host 91f3f452ffab
[2025-03-16T19:08:42.137+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='print_random_quote' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T19:08:22.500968+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T19:08:22.500968+00:00'
[2025-03-16T19:08:42.140+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-16T19:08:42.341+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1097 InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.quotable.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-03-16T19:08:42.389+0000] {logging_mixin.py:190} INFO - Quote of the day: "A rolling stone gathers no moss."
[2025-03-16T19:08:42.392+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-16T19:08:42.419+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-16T19:08:42.420+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=welcome_dag, task_id=print_random_quote, run_id=manual__2025-03-16T19:08:22.500968+00:00, execution_date=20250316T190822, start_date=20250316T190841, end_date=20250316T190842
[2025-03-16T19:08:42.555+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-16T19:08:42.616+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T19:08:42.621+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
